apiVersion: v1
kind: ConfigMap
metadata:
  name: topic-service-config
  namespace: yt-planner
data:
  SERVER_PORT: "8081"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-svc:9092"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info"
