# infra/k8s/base/secrets/secret-provider.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
  namespace: yt-planner
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "<IDENTITY_CLIENT_ID>"
    keyvaultName: "kv-yt-planner"
    objects: |
      array:
        - |
          objectName: postgres-password
          objectType: secret
        - |
          objectName: openai-api-key
          objectType: secret
        - |
          objectName: redis-password
          objectType: secret
    tenantId: "<your-azure-tenant-id>"
  secretObjects:
    - secretName: db-credentials
      type: Opaque
      data:
        - objectName: postgres-password
          key: POSTGRES_PASSWORD
    - secretName: openai-api-key
      type: Opaque
      data:
        - objectName: openai-api-key
          key: OPENAI_API_KEY